#SERVER SETTINGS
server:
  port: 8080
  zone-id: UTC

#SPRING SETTINGS
spring:
  data:
    mongodb:
      uri: 'mongodb://dev_mongo:dev_password@localhost:27170/aggregator'
      auto-index-creation: true

#CLOUDINARY_SETTINGS
products-images-location: dev/images
